---

kolla_selinux_policies_aodh:
  aodh_api:
    enabled: "{{ enable_aodh | default(true) | bool }}"
    groups:
      - "controllers"
      - "control"
    description: "Dedicated SELinux domain for Aodh API"
    domain: "kolla_aodh_api_t"
    exec_type: "kolla_aodh_api_exec_t"
    requires:
      - "type container_runtime_t;"
      - "type port_t;"
      - "class tcp_socket { name_bind name_connect };"
    allow_rules:
      - "allow kolla_aodh_api_t port_t:tcp_socket { name_bind name_connect };"
