---
kolla_selinux_policies_neutron:
  # ----------------------------------------
  # Neutron Control Plane (API)
  # ----------------------------------------
  neutron_server:
    enabled: "{{ enable_neutron | default(true) | bool }}"
    # group: "{{ neutron_server_group | default('neutron-server') }}"
    groups:
      - "controllers"
    description: "Dedicated SELinux domain for Neutron API Server"
    domain: "kolla_neutron_server_t"
    exec_type: "kolla_neutron_server_exec_t"
    requires:
      - "type container_runtime_t;"
      - "type port_t;"
      - "class tcp_socket { name_bind name_connect };"
    allow_rules:
      - "allow kolla_neutron_server_t port_t:tcp_socket { name_bind name_connect };"

  # ----------------------------------------
  # Neutron Network Node Agents
  # ----------------------------------------
  neutron_dhcp_agent:
    enabled: "{{ enable_neutron_dhcp | default(true) | bool }}"
    groups:
      - "network"
    description: "Dedicated SELinux domain for Neutron DHCP Agent"
    domain: "kolla_neutron_dhcp_t"
    exec_type: "kolla_neutron_dhcp_exec_t"
    requires:
      - "type container_runtime_t;"
      - "type var_run_t;"
      - "type proc_net_t;"
      - "class capability { net_admin net_raw sys_admin };"
      - "class file { read open getattr };"
      - "class netif { ingress egress };"
    allow_rules:
      - "allow kolla_neutron_dhcp_t self:capability { net_admin net_raw sys_admin };"
      - "allow kolla_neutron_dhcp_t var_run_t:dir { read search getattr };"
      - "allow kolla_neutron_dhcp_t proc_net_t:file { read open getattr };"
      - "allow kolla_neutron_dhcp_t self:netif { ingress egress };"

  neutron_l3_agent:
    enabled: "{{ enable_neutron_l3 | default(true) | bool }}"
    # group: "{{ neutron_openvswitch_agent_group | default('neutron-openvswitch-agent') }}"
    groups:
      - "network"
    description: "Dedicated SELinux domain for Neutron L3 Routing Agent"
    domain: "kolla_neutron_l3_t"
    exec_type: "kolla_neutron_l3_exec_t"
    requires:
      - "type container_runtime_t;"
      - "type tun_tap_device_t;"
      - "class capability { net_admin sys_admin net_raw };"
      - "class chr_file { read write open ioctl getattr };"
      - "class netif { ingress egress };"
    allow_rules:
      - "allow kolla_neutron_l3_t self:capability { net_admin sys_admin net_raw };"
      - "allow kolla_neutron_l3_t tun_tap_device_t:chr_file { read write open ioctl getattr };"
      - "allow kolla_neutron_l3_t self:netif {ingress egress };"

  # ----------------------------------------
  # Neutron Compute Node Agents (OVS)
  # container neutron_ovn_metadata_agent
  # ----------------------------------------
  neutron_openvswitch_agent:
    enabled: "{{ enable_neutron_openvswitch | default(true) | bool }}"
    # OVS agents must run on BOTH network routing nodes and baremetal compute nodes
    # group: "{{ neutron_openvswitch_agent_group | default('neutron-openvswitch-agent') }}"
    groups:
      - "network"
      - "compute"
    description: "Dedicated SELinux domain for Neutron OVS Agent"
    domain: "kolla_neutron_ovs_agent_t"
    exec_type: "kolla_neutron_ovs_agent_exec_t"
    requires:
      - "type container_runtime_t;"
      - "type var_run_t;"
      - "type net_conf_t;"
      - "class capability { net_admin sys_admin };"
      - "class sock_file { create setattr write unlink };"
      - "class file { read getattr open };"
    allow_rules:
      - "allow kolla_neutron_ovs_agent_t self:capability { net_admin sys_admin };"
      - "allow kolla_neutron_ovs_agent_t var_run_t:sock_file { create setattr write unlink };"
      - "allow kolla_neutron_ovs_agent_t net_conf_t:file { read getattr open };"
